import "dotenv/config";
import { prisma } from "../src/lib/prisma";

const studies = [
  {
    slug: "lansing-housing-commission",
    boardName: "Lansing Housing Commission",
    category: "Housing",
    date: "June 10, 2026",
    published: true,
    summary: "The Lansing Housing Commission's operations exemplify how housing privatization systematically extracts wealth from communities while claiming to serve them. The SK Investment Group transaction, tax credit syndication through Cinnaire, and federal grant accumulation represent a coordinated shift from maximizing affordable housing units to maximizing financial returns for private partners. LHC's operational model violates every ICA cooperative principle and all five ownership question dimensions show extractive characteristics.",
    stats: [
      { value: "51", label: "Families evicted" },
      { value: "14", label: "Evicted in one day" },
      { value: "25%", label: "Eviction rate" },
      { value: "84", label: "Net units lost" },
      { value: "85+", label: "Children displaced" },
      { value: "$17.7M", label: "Sale proceeds" },
      { value: "$357K", label: "Cost per unit built" },
      { value: "$87.6K", label: "Sale price per unit" },
    ],
    principles: [
      { num: 1, name: "Voluntary and Open Membership", violation: "51 families evicted — 14 in a single day — through court proceedings with no voluntary exit process. New residents selected by private landlord criteria, not community need.", evidence: "MiCOURT records: 51 eviction cases filed by SK Lansing, all marked CLOSED." },
      { num: 2, name: "Democratic Member Control", violation: "Residents had no vote in the decision to sell their homes. 40 families expressed interest in purchasing; only 8 qualified. No documented resident consultation in the sale process.", evidence: "No resident representation on LHC board during sale process." },
      { num: 3, name: "Member Economic Participation", violation: "Residents received zero share of $17.7M in sale proceeds. Families who built community through residency received nothing. Capital gains captured entirely by LHC and transferred to private entity.", evidence: "$17.7M sale proceeds; zero resident benefit sharing; LHC accumulates $30M+ including federal grants." },
      { num: 4, name: "Autonomy and Independence", violation: "Community lost autonomous control over housing. Properties now controlled by a Florida investment firm (SK Investment Group, 1,500+ units across multiple states). 20-year covenant creates dependency, not autonomy.", evidence: "SK Investment Group operates from Florida; Lansing properties managed as part of external investment portfolio." },
      { num: 5, name: "Education, Training, and Information", violation: "Residents were told 'very few' would need to relocate. Reality: 25% eviction rate. FOIA requests blocked with $807.60 fees using wrong legal test.", evidence: "Promises of minimal displacement contradicted by 51 eviction filings." },
      { num: 6, name: "Cooperation Among Cooperatives", violation: "LHC partnered with extractive private capital rather than community land trusts, resident cooperatives, or community development corporations. No exploration of cooperative ownership transition.", evidence: "Sale to private Limited Dividend Housing Association rather than community-controlled entity." },
      { num: 7, name: "Concern for Community", violation: "85+ school-age children displaced mid-academic year. Community stability destroyed through mass evictions. Estimated $1.3M cost to school district. Local wealth extracted to external investors.", evidence: "Educational disruption during school year; community assets transferred to external ownership." },
    ],
    ownership: [
      { question: "Who owns it?", before: "Public — LHC (community asset)", after: "SK Investment Group (private capital)", assessment: "extractive" },
      { question: "Who has power?", before: "LHC Board (publicly accountable)", after: "SK Group management (external private entity)", assessment: "extractive" },
      { question: "Who benefits?", before: "202 low-income Lansing families", after: "SK shareholders, Cinnaire, LHC via management fees", assessment: "extractive" },
      { question: "Who does the work?", before: "LHC staff, local contractors", after: "LHC potentially contracted back as managers — circular extraction", assessment: "extractive" },
      { question: "Who makes the rules?", before: "HUD regulations, public accountability", after: "Private landlord-tenant law, SK corporate policy", assessment: "extractive" },
    ],
    bottomLines: [
      { dimension: "People", impact: "negative", description: "51 families displaced, 85+ children disrupted mid-school-year, community social networks destroyed through mass eviction." },
      { dimension: "Planet", impact: "negative", description: "Existing housing stock underutilized due to evictions. Transportation impacts from family displacement. Inefficient use of publicly-built infrastructure." },
      { dimension: "Prosperity", impact: "negative", description: "$17.7M in community wealth transferred to private capital. Ongoing federal subsidies flow to private entity through 2042. Local economic multiplier effects reduced." },
      { dimension: "Purpose", impact: "negative", description: "Public housing mission corrupted into private profit generation. Affordability preservation used as cover for wealth extraction. Democratic housing provision replaced with market-based exclusion." },
    ],
    scoreTransparency: "high-risk",
    scoreConflicts: "high-risk",
    scoreMission: "high-risk",
    scoreDemocraticControl: "high-risk",
    scoreOversight: "concerning",
    sections: [
      {
        eyebrow: "The pattern",
        heading: "Privatization over people",
        description: "",
        items: [
          { label: "Tax credit syndication", desc: "Partnering with Cinnaire to monetize federal tax credits rather than direct housing development." },
          { label: "Asset disposition", desc: "Selling 202 public housing units to generate $17.7M in liquid capital at $87,600/unit while construction cost $357,000/unit." },
          { label: "Federal grant accumulation", desc: "Collecting $17M+ in HUD Capital Fund grants while reducing housing stock from 833 units (2020) to 66 units (2025)." },
          { label: "Management contracting", desc: "Capital City Property Management LLC established to retain management-fee income on sold properties — sell then manage the same asset." },
        ],
      },
      {
        eyebrow: "Conflict of interest",
        heading: "Board members on both sides of transactions",
        description: "Multiple board members hold financial interests in organizations that do business with the Commission — and vote on those transactions without recusal.",
        items: [
          { label: "Ashlee Barker (Board VP)", desc: "Serves as Vice President at Cinnaire — the company financing the Commission's downtown projects. Moved land-purchase votes and seconded compensation votes without stepping aside (2023–2025)." },
          { label: "Emma Henry (Board Chair)", desc: "Executive Director of Capital Area Housing Partnership — a housing developer competing for Commission deals. Moved director's compensation and bonus votes (2023–2025). Only recused from one 2025 vote involving a competing bidder." },
          { label: "Doug Fleming (Executive Director)", desc: "Signed the Oliver Gardens II deal (August 2025) representing both the private company and the Commission simultaneously. Receives a 30% bonus set by the board he reports to." },
        ],
      },
    ],
    recommendations: [
      "Establish a Lansing Community Land Trust with resident board representation as the default recipient for any future LHC asset disposition",
      "Immediately restore the Resident Advisory Board — its dissolution violates 24 CFR 903.13 federal requirements",
      "Reform LHC governance to require resident representation on the board with voting rights",
      "Require mandatory recusal and public disclosure whenever a board member has a financial relationship with an entity doing business with the Commission",
      "Use remaining sale proceeds to expand community-controlled affordable housing rather than accumulate liquid capital",
      "Independent forensic audit of all LHC financial flows since 2018, including Cinnaire partnerships and CCRCI transactions",
    ],
    sources: [
      "Rhinoceros Media. \"Lansing's Public Housing Red Flags.\"",
      "Rhinoceros Media. \"Five Records Requests to the Lansing Housing Commission, Zero Records Produced.\"",
      "MiCOURT records — SK Lansing eviction filings (51 cases, all marked CLOSED).",
      "International Cooperative Alliance. \"Statement on the Cooperative Identity.\" ICA, 1995.",
      "Democracy at Work Institute. \"Community Ownership Handbook.\" DAWI, 2023.",
      "HUD Capital Fund grant records (via federal FOIA).",
    ],
    sourceUrls: ["https://rhinocerosmedia.org/lhc-red-flags", "https://rhinocerosmedia.org/lhc-records-access-pattern"],
  },

  {
    slug: "ingham-county-land-bank",
    boardName: "Ingham County Land Bank",
    category: "Land Use",
    date: "June 2026",
    published: true,
    summary: "The Ingham County Land Bank was created to return vacant and tax-foreclosed property to productive use. Over 20 years its operations have produced the opposite: a 2.7-to-1 demolition-to-creation ratio, a 472-parcel landholding in a city with a severe housing shortage, and a procurement pipeline that consistently routes public funds to a small circle of preferred partners without competitive bidding.",
    stats: [
      { value: "2.7:1", label: "Demolitions per unit created" },
      { value: "472", label: "Parcels owned in Lansing" },
      { value: "$976K", label: "Demolition spending (2024)" },
      { value: "$1.5M", label: "Grant to post-selection LLC" },
      { value: "$1", label: "Insider property acquisition" },
      { value: "0", label: "Competitive bids documented" },
      { value: "22 min", label: "Average board meeting" },
      { value: "5 yrs", label: "One dissenting vote recorded" },
    ],
    principles: [
      { num: 1, name: "Voluntary and Open Membership", violation: "Residents have no meaningful choice when the Land Bank acquires tax-foreclosed properties from their neighborhood or demolishes adjacent structures. Community members cannot opt into or out of Land Bank decisions affecting their blocks.", evidence: "Land Bank removes homeless encampments from its 472 vacant parcels without alternative proposals per board meeting notes." },
      { num: 2, name: "Democratic Member Control", violation: "Board meetings average 22–56 minutes with zero public comment documented in approximately 20 meetings (2020–2026). Only one dissenting vote recorded across five years. Decisions made unanimously without substantive public deliberation.", evidence: "Board minutes 2020–2026 show zero public comment periods; one non-unanimous vote across all meetings reviewed." },
      { num: 3, name: "Member Economic Participation", violation: "Public funds ($976K demolition grants, $1.5M+ in redirected grants) flow to insider preferred partners without competitive bidding. Community receives demolitions and vacant lots rather than housing.", evidence: "Pleasant Grove project: $1.5M in county grants redirected to LLC formed 3 days after selection; no competitive bidding documented." },
      { num: 4, name: "Autonomy and Independence", violation: "Every board member occupies overlapping roles in county government — three of five are county commissioners who also hold fiscal or zoning authority over Land Bank operations. Treasurer controls tax-foreclosure pipeline that supplies inventory.", evidence: "Alan Fox (Chair): Ingham County Treasurer — controls supply. Rawley Van Fossen (Treasurer): City planning director — issues demolition permits on properties Land Bank sells." },
      { num: 5, name: "Education, Training, and Information", violation: "No public dashboard showing parcel acquisitions, sales, prices, or buyer identities. Blanket authorizations issued to preferred buyers without specifying which properties. Community cannot track what is acquired, held, or sold.", evidence: "April 2025: Board authorized Cooney Homes to purchase multiple parcels without identifying specific properties." },
      { num: 6, name: "Cooperation Among Cooperatives", violation: "Directs public-funded parcels to CAHP (circular arrangement where Emma Henry runs both CAHP and the Housing Commission), Cooney Homes, and Allen Edwin rather than cooperative housing alternatives or community land trusts.", evidence: "CAHP receives below-market acquisitions ($5,610 average) while paying Land Bank quarterly rental-management fees." },
      { num: 7, name: "Concern for Community", violation: "2.7-to-1 demolition ratio during Michigan's 119,000-unit housing deficit. 472 idle parcels while Lansing rents rise 25.3%. Renovated homes sold at market rate ($145K-$200K) using public funds with no affordability restrictions.", evidence: "15-year record (2005–2020): ~800 demolished vs. 297 units created. Sparrow-donated houses renovated at zero acquisition cost, sold at $925K total." },
    ],
    ownership: [
      { question: "Who owns it?", before: "Ingham County (public, tax-foreclosed)", after: "Preferred private buyers — CAHP, Cooney Homes, Allen Edwin — without competitive process", assessment: "extractive" },
      { question: "Who has power?", before: "Board (nominally public)", after: "Same board members in their other government roles — self-referential authority", assessment: "extractive" },
      { question: "Who benefits?", before: "Community (statutory purpose)", after: "CAHP, preferred developers, HOA self-management entities controlled by Land Bank staff", assessment: "extractive" },
      { question: "Who does the work?", before: "Land Bank staff, contracted demolition crews", after: "Same staff also control HOA boards and manage properties they dispose — circular accountability", assessment: "extractive" },
      { question: "Who makes the rules?", before: "Michigan Land Bank Fast Track Act (PA 258) + county commission", after: "Board members (also county commissioners) setting their own oversight with no federal inspector general", assessment: "extractive" },
    ],
    bottomLines: [
      { dimension: "People", impact: "negative", description: "2.7:1 demolition ratio reduces housing supply during crisis. 472 parcels idle while Lansing rents rise 25%. No affordability restrictions on market-rate renovations." },
      { dimension: "Planet", impact: "mixed", description: "Demolition removes deteriorated structures but leaves vacant lots. No documented green or energy-efficient development. Large land inventory sits unproductive." },
      { dimension: "Prosperity", impact: "negative", description: "Public funds ($1.5M+) flow to insider partners without competition. Below-market parcel sales to preferred buyers. Community receives demolitions; preferred partners receive subsidized assets." },
      { dimension: "Purpose", impact: "negative", description: "Statutory mission (return property to productive use) contradicted by 20-year demolition-heavy record. Land Bank operates as demolition contractor with preferred-partner real estate sales, not a housing development institution." },
    ],
    scoreTransparency: "high-risk",
    scoreConflicts: "high-risk",
    scoreMission: "high-risk",
    scoreDemocraticControl: "high-risk",
    scoreOversight: "high-risk",
    sections: [
      {
        eyebrow: "Board composition",
        heading: "Every member has a conflicting role",
        description: "Three of five board members are also Ingham County commissioners — they hold fiscal authority over the Land Bank's budget while sitting on the board it funds.",
        items: [
          { label: "Alan Fox — Chair (ex officio)", desc: "Ingham County Treasurer. Controls tax-foreclosure pipeline supplying Land Bank inventory. Co-owned Practical Political Consulting with board member Mark Grebner before Fox became Treasurer." },
          { label: "Rawley Van Fossen — Treasurer", desc: "City of Lansing Director of Economic Development and Planning. Issues demolition permits on properties Land Bank sells. Former CAHP executive director — CAHP is a preferred Land Bank partner." },
          { label: "Emma Henry — Member", desc: "Executive Director, Capital Area Housing Partnership. CAHP receives below-market Land Bank parcels. Henry also chairs the Lansing Housing Commission, creating a three-way circular arrangement." },
        ],
      },
      {
        eyebrow: "Insider pipeline",
        heading: "Preferred partners, no competitive process",
        description: "",
        items: [
          { label: "Pleasant Grove — $1.5M grant to newly formed LLC", desc: "Brent Forsberg selected via two-response RFP (September 2024). Holmes & Pleasant Grove LLC formed June 3, 2025 — three days after selection. $1.5M in county grants redirected to the new entity. Additional $4,500/month in personal consulting payments (October–December 2025)." },
          { label: "122 Allen Street — $1 staff acquisition", desc: "Land Bank acquired a gas-damaged house from its own Garden Program Coordinator for $1 (December 2024). Demolished with public funds. Cleared lot sold for $7,500 to preferred developer under blanket authorization. No conflict-disclosure rule covered this." },
          { label: "HOA self-management", desc: "Land Bank attorney, executive director, and real estate specialist control HOA boards for Genesee Pointe and Pointe West while Land Bank pays HOA dues on unsold units at $165/month per unit." },
        ],
      },
    ],
    recommendations: [
      "Require competitive bidding for all property dispositions above a defined threshold — with minimum 30-day public notice",
      "Prohibit board members from simultaneously serving in roles that supply, receive, or permit Land Bank properties",
      "Mandate income-restricted affordability covenants on all properties renovated using public grants",
      "Require a forensic audit of grant expenditures — modeled on the Detroit Land Bank audit (2020) which uncovered $50.8M in unapproved payments",
      "Establish a public dashboard showing every parcel acquired, held, demolished, and sold — with dates, prices, and buyer identities",
      "Set a moratorium on demolitions until a housing creation plan with measurable unit targets is adopted",
    ],
    sources: [
      "Rhinoceros Media. \"Demolition Is the Ingham County Land Bank's Current Business Model.\"",
      "Rhinoceros Media. \"The Ingham County Land Bank's Insider Pipeline.\"",
      "Michigan Land Bank Fast Track Act (PA 258) — statutory purpose statement.",
      "Ingham County Land Bank board minutes and resolutions (2020–2026), obtained via FOIA.",
    ],
    sourceUrls: ["https://rhinocerosmedia.org/lansing-land-bank-demolition-business", "https://rhinocerosmedia.org/lansing-land-bank-insider-pipeline"],
  },

  {
    slug: "flock-surveillance",
    boardName: "Board of Police Commissioners / Flock Surveillance",
    category: "Surveillance",
    date: "April–June 2026",
    published: true,
    summary: "In September 2025, Lansing deployed approximately 20 Flock Safety automatic license plate reader cameras citywide without any documented City Council vote, Board of Police Commissioners review, or written policy. The first public discussion occurred April 23, 2026 — seven months later. No civilian oversight mechanism has been documented. Flock Safety's national network has a documented record of misuse including protest surveillance, immigration enforcement, and domestic abuse facilitation.",
    stats: [
      { value: "20", label: "Cameras deployed" },
      { value: "7 mo.", label: "Before public discussion" },
      { value: "0", label: "Board votes recorded" },
      { value: "0", label: "Written policies" },
      { value: "0", label: "Civilian oversight bodies" },
      { value: "20B+", label: "Vehicle scans/month (national)" },
      { value: "50+", label: "Agencies surveilling protests" },
      { value: "30+", label: "Localities cancelled (2025)" },
    ],
    principles: [
      { num: 1, name: "Voluntary and Open Membership", violation: "Residents had no vote or voice in deploying surveillance infrastructure in public space. The program became active before any public awareness and with no mechanism for community opt-out or input.", evidence: "Program deployed September 2025; first public discussion April 23, 2026 — 7 months of operation without community knowledge." },
      { num: 2, name: "Democratic Member Control", violation: "No City Council vote, no Board of Police Commissioners review, no written policy — all documented at the April 23 hearing. The program bypassed every formal democratic authorization channel.", evidence: "Chief Backus confirmed: 'There is no civilian oversight of the program, no review by the Board of Police Commissioners.'" },
      { num: 3, name: "Member Economic Participation", violation: "Community bears the surveillance costs ($2,500–3,500/camera/year in public funds) and the privacy risk without any consent mechanism or shared benefit. Benefits flow primarily to Flock Safety ($7.5B valuation).", evidence: "Flock raised $275M in Series F (March 2025) at $7.5B valuation. Lansing's contract terms and cost not publicly disclosed." },
      { num: 4, name: "Autonomy and Independence", violation: "A $7.5B private corporation controls the technology, the data network, and the terms of access. Lansing has no independent audit capability of its own data within Flock's national network.", evidence: "Flock processes 20+ billion vehicle scans monthly nationally. Lansing's audit log access and federal data-sharing status remain unknown." },
      { num: 5, name: "Education, Training, and Information", violation: "Program operated for 7 months without public disclosure. No written policy existed at time of first public hearing. No FOIA guidance established — City Attorney stated the question 'has not come up.'", evidence: "April 23 committee hearing: no written policy materials distributed; Chief described safeguards verbally only." },
      { num: 6, name: "Cooperation Among Cooperatives", violation: "No coordination with civil liberties organizations, privacy rights groups, community oversight bodies, or peer cities that have successfully implemented accountability frameworks. Ferndale's cancellation (November 2025) ignored as precedent.", evidence: "Bipartisan Michigan HB 5492-5493 proposing 14-day retention and quarterly reporting still in House Judiciary as of April 2026." },
      { num: 7, name: "Concern for Community", violation: "Nationally, Flock's network is documented facilitating protest surveillance, immigration enforcement against statute, domestic abuse, and abortion surveillance. Lansing deployed with no local safeguards against any of these known failure modes.", evidence: "50+ agencies conducted protest-related searches (EFF analysis). Texas deputy tracked abortion patient. 4,000+ ICE/immigration queries through national network." },
    ],
    ownership: [
      { question: "Who owns it?", before: "Public space (streets, public right-of-way)", after: "Data network partially transferred to Flock Safety's 20B+ scan/month national infrastructure", assessment: "extractive" },
      { question: "Who has power?", before: "City Council / Board of Police Commissioners (democratic authorization)", after: "Police Chief with no documented authorization chain; Flock corporate policy", assessment: "extractive" },
      { question: "Who benefits?", before: "Intended: public safety", after: "Flock Safety ($7.5B valuation), law enforcement agencies with data access; community bears surveillance costs", assessment: "mixed" },
      { question: "Who does the work?", before: "City police", after: "Flock Safety operates the network; city has no independent audit capability", assessment: "extractive" },
      { question: "Who makes the rules?", before: "City Charter / Council vote", after: "Chief Backus verbally; Flock corporate policy; no written local rules established", assessment: "extractive" },
    ],
    bottomLines: [
      { dimension: "People", impact: "negative", description: "Surveillance without consent or democratic authorization. Nationally documented targeting of protesters, immigrants, domestic abuse victims, and abortion patients with no local safeguards." },
      { dimension: "Planet", impact: "insufficient", description: "Insufficient evidence in available reporting to assess environmental impact." },
      { dimension: "Prosperity", impact: "mixed", description: "Public funds flow to Flock Safety ($2,500-3,500/camera/year). Potential crime deterrence benefit not assessed against privacy and civil liberties costs." },
      { dimension: "Purpose", impact: "negative", description: "Public safety mission requires democratic authorization and accountability. Deployment without policy, oversight, or community consent inverts the purpose of a police oversight board." },
    ],
    scoreTransparency: "high-risk",
    scoreConflicts: "insufficient",
    scoreMission: "concerning",
    scoreDemocraticControl: "high-risk",
    scoreOversight: "high-risk",
    sections: [
      {
        eyebrow: "Documented misuse nationally",
        heading: "Known failure modes — no local safeguards",
        description: "Lansing deployed with none of the safeguards that peer cities implemented after documenting these specific failure modes.",
        items: [
          { label: "Illinois — immigration enforcement violation", desc: "Flock facilitated CBP access to ALPR data in violation of a 2023 Illinois statute restricting immigration enforcement cooperation." },
          { label: "Kansas — domestic abuse", desc: "Police chief conducted 228 Flock searches tracking an ex-partner's vehicle." },
          { label: "Texas — abortion surveillance", desc: "Deputy used the 83,000-camera national network to track a woman who had obtained an abortion. Logged as: 'had an abortion, search for female.'" },
          { label: "National (EFF) — protest surveillance", desc: "Over 50 agencies conducted protest-related surveillance searches. 4,000+ ICE/immigration queries documented through national network." },
          { label: "Ferndale, MI — cancelled November 2025", desc: "Ferndale terminated its Flock program after discovering the national lookup feature was active 'when it wasn't supposed to be.' At least 30 U.S. localities cancelled since early 2025." },
        ],
      },
    ],
    recommendations: [
      "Require a City Council vote before deploying any new surveillance technology — retroactively ratify or terminate the existing Flock deployment",
      "Adopt a written Surveillance Technology Use Policy with data retention limits aligned with HB 5492-5493, prohibited uses, and quarterly public audit reports",
      "Establish civilian oversight with subpoena power — Board of Police Commissioners must review all surveillance programs on a documented schedule",
      "Prohibit sharing Lansing Flock data with federal immigration enforcement agencies without a warrant",
      "Publish searchable audit logs showing who queried Lansing cameras, when, and for what stated purpose",
    ],
    sources: [
      "Rhinoceros Media. \"Who Owns and Funds the Cameras Watching Lansing.\"",
      "Rhinoceros Media. \"Lansing's First Flock Briefing.\"",
      "Rhinoceros Media. \"What the Evidence and the Record Show About Flock's Cameras.\"",
      "Electronic Frontier Foundation. ALPR data analysis, 2025.",
      "University of Washington. Flock network access study.",
    ],
    sourceUrls: ["https://rhinocerosmedia.org/flock-ownership", "https://rhinocerosmedia.org/flock-evidence-and-record"],
  },

  {
    slug: "lansing-chamber-pac",
    boardName: "Lansing Regional Chamber & LRC-PAC",
    category: "Finance",
    date: "2024–2026",
    published: true,
    summary: "The Lansing Regional Chamber of Commerce has operated a PAC for 48 years that funds the majority of city council members and then advocates before those same members on zoning, development, and contract decisions. Its 2024 IRS Form 990 reports $0 in political campaign activity while distributing $30,750 in council contributions. The same PAC claims federal registration but no FEC filings appear in the database. The Chamber's leadership is embedded in a $43.5 million dark money network connected to Consumers Energy.",
    stats: [
      { value: "6 of 8", label: "Council members funded" },
      { value: "$30,750", label: "PAC contributions (2024–25)" },
      { value: "$0", label: "Political spending on IRS 990" },
      { value: "92%", label: "Endorsement win rate (primary)" },
      { value: "$43.5M", label: "Consumers Energy dark money" },
      { value: "58%", label: "Deep Green letters from affiliates" },
      { value: "48 yrs", label: "PAC operating history" },
      { value: "0", label: "FEC filings found" },
    ],
    principles: [
      { num: 1, name: "Voluntary and Open Membership", violation: "Community members had template letters submitted in their names through the Chamber's advocacy platform without evidence of self-enrollment. Residents opposing Deep Green (200+) were outnumbered in the official record by Chamber-manufactured letters.", evidence: "4 of 12 Deep Green support letters show 'loopback' enrollment patterns — accounts enrolled by administrators, not self-organized." },
      { num: 2, name: "Democratic Member Control", violation: "6 of 8 council members funded by an entity that advocates before them; this structurally prevents independent democratic decision-making on Chamber-relevant votes. PAC endorsement shapes elections (92% primary win rate), which shapes who makes the decisions.", evidence: "LRC-PAC distributed $30,750 to 6 of 8 sitting council members; Mayor Schor received $1,500." },
      { num: 3, name: "Member Economic Participation", violation: "Chamber members fund the PAC; PAC funds Council members; Council approves Chamber-preferred development projects. Benefits flow to preferred developers and the Chamber's consulting ecosystem, not to the broader community.", evidence: "Deep Green: Chamber-funded Council majority approved project despite 200+ community members opposing at February 10 meeting." },
      { num: 4, name: "Autonomy and Independence", violation: "Council members receiving PAC funds cannot be fully independent when Chamber interests appear before them. City attorney conflicts in narrowing conflict standards (Garza case) further compromise independence of oversight bodies.", evidence: "Adrian Hemond simultaneously advises Mayor, city unions, and Chamber PAC funding 7 of 8 council members — conflict built into consulting structure." },
      { num: 5, name: "Education, Training, and Information", violation: "Chamber's IRS 990 reports $0 political spending despite distributing $30,750. No FEC filings found despite claimed federal registration. $311,344 in 'Other fees for services' with no vendor names disclosed.", evidence: "2024 Form 990: $0 political campaign activity reported. FEC database search: no LRC-PAC filings found." },
      { num: 6, name: "Cooperation Among Cooperatives", violation: "Chamber coordinates with Consumers Energy dark money network, Bellwether PR astroturf operations, and $43.5M anonymous funding infrastructure — not cooperative alternatives or community organizations.", evidence: "Nine BWL employees donated $6,000 to LRC-PAC within 48 hours (March 2022). CFO Heather Shawa joined Chamber 2026 Board and testified for Deep Green." },
      { num: 7, name: "Concern for Community", violation: "Manufactured consent campaigns present Chamber-member views as community consensus. 200+ residents opposed Deep Green at public hearing while Chamber engineered apparent support. Dark money network obscures who is influencing community decisions.", evidence: "Chamber homepage linked directly to Deep Green advocacy campaign without disclosure; 58% of support letters came from Chamber-affiliated individuals." },
    ],
    ownership: [
      { question: "Who owns it?", before: "Community (city zoning, development decisions, public contracts)", after: "Chamber-funded council majority that approves Chamber-preferred outcomes", assessment: "extractive" },
      { question: "Who has power?", before: "Elected council (nominally)", after: "Chamber PAC through funding and endorsement — 92% win rate shapes who holds the seats", assessment: "extractive" },
      { question: "Who benefits?", before: "Community", after: "Chamber members, preferred developers, political consulting firms ($19,034 to Greenlee in 2025)", assessment: "extractive" },
      { question: "Who does the work?", before: "City staff, elected officials", after: "Chamber PAC, Bellwether PR, dark money network operators — behind-the-scenes influence operation", assessment: "extractive" },
      { question: "Who makes the rules?", before: "Charter and state law", after: "City attorney narrowing conflict standards; PAC funding of those who enforce the rules", assessment: "extractive" },
    ],
    bottomLines: [
      { dimension: "People", impact: "negative", description: "Manufactured public consent undermines genuine community participation. 200+ residents opposed Deep Green but faced Chamber-manufactured appearance of support." },
      { dimension: "Planet", impact: "mixed", description: "Chamber advocacy promoted high-energy data center infrastructure over community environmental preference. Dark money connections extend to Consumers Energy ratepayer interests." },
      { dimension: "Prosperity", impact: "negative", description: "$43.5M dark money network extracts community trust and democratic legitimacy. PAC funds flow to political consulting rather than community benefit." },
      { dimension: "Purpose", impact: "negative", description: "Chamber business development mission corrupts civic governance by funding oversight of decisions the Chamber wants to influence — a structural conflict operating in public view." },
    ],
    scoreTransparency: "high-risk",
    scoreConflicts: "high-risk",
    scoreMission: "insufficient",
    scoreDemocraticControl: "high-risk",
    scoreOversight: "high-risk",
    sections: [
      {
        eyebrow: "The dark money network",
        heading: "$43.5M from Consumers Energy reaches City Hall",
        description: "The Chamber is one node in a larger network. Consumers Energy funneled $43.5M (2014–2017) through anonymous nonprofits. That network reaches directly into Lansing city decisions.",
        items: [
          { label: "Reid Felsing", desc: "Attorney and dark money network architect. Quote: 'The beauty of the C4 is the anonymity of money coming in.' Appointed to Eaton County District Court bench (January 2025)." },
          { label: "Adrian Hemond", desc: "CEO, Grassroots Midwest consulting. Simultaneously advises the Mayor, city unions, and the Chamber PAC that funds 7 of 8 council members. Conflict embedded in the consulting structure." },
          { label: "Josh Hovey / Bellwether PR", desc: "PAC committee member and former Planning Commissioner. Now lobbies the Planning Commission as paid consultant. Also managed the Michigan for Responsible Data Centers astroturf coalition while representing Deep Green." },
        ],
      },
    ],
    recommendations: [
      "Require council members to disclose PAC funding from organizations appearing before them and recuse on relevant votes",
      "Adopt a small-donor public financing ordinance — the route Seattle and San Jose used to dilute concentrated PAC influence",
      "IRS should audit Chamber 990 — $0 political spending claim is inconsistent with 48 years of documented PAC operations",
      "Require disclosure of all advocacy platform campaigns generating template letters submitted as public comment",
      "Pass a proactive disclosure ordinance — publish meeting communications before being FOIA'd, making manufactured consent visible in real time",
    ],
    sources: [
      "Rhinoceros Media. \"How the Chamber's PAC Shapes Who Governs and What Gets Built\" (6-part series).",
      "Rhinoceros Media. \"How Consumers Energy's $43 Million Dark Money Operation Reaches Lansing City Hall.\"",
      "Michigan Department of State campaign finance filings — LRC-PAC (2024–2025).",
      "IRS Form 990, Lansing Regional Chamber of Commerce (2024).",
      "FEC committee database search — no LRC-PAC filings found.",
    ],
    sourceUrls: ["https://rhinocerosmedia.org/lrc-pac-chamber-machine", "https://rhinocerosmedia.org/consumers-energy-dark-money-lansing"],
  },

  {
    slug: "board-of-ethics",
    boardName: "Lansing Board of Ethics",
    category: "Ethics",
    date: "April 2026",
    published: true,
    summary: "Four residents filed documented conflict-of-interest complaints against Council Member Jeremy Garza, citing his $126,742 annual salary from the Michigan Pipe Trades Association while voting on union construction work as a council member. The Board of Ethics declined to issue any opinion — by voice vote, without recording a roll call — after the city attorney redefined the legal standard from the Charter's 'any income or benefit, directly or indirectly' to a narrower requirement of a 'direct contractual relationship.' No precedent was established for future situations.",
    stats: [
      { value: "4", label: "Complaints filed" },
      { value: "0", label: "Opinions issued" },
      { value: "1", label: "Voice vote taken" },
      { value: "0", label: "Roll call recorded" },
      { value: "$126,742", label: "Garza annual salary (Pipe Trades)" },
      { value: "0", label: "Precedent established" },
    ],
    principles: [
      { num: 1, name: "Voluntary and Open Membership", violation: "Four community members voluntarily used the legitimate ethics process. The Board's voice vote without roll call means individual positions are not part of the public record — complainants cannot know who voted to decline.", evidence: "Board declined by voice vote on April 14, 2026 — no individual positions recorded." },
      { num: 2, name: "Democratic Member Control", violation: "A voice vote on a conflict-of-interest ruling removes democratic accountability from the oversight body itself. The same mechanism that should create accountability operates without a traceable record.", evidence: "Board of Ethics meeting minutes: voice vote recorded, no individual members' positions noted." },
      { num: 3, name: "Member Economic Participation", violation: "$126,742 in union salary flows to a council member who votes on union construction contracts and development approvals. The Board declined to define whether this constitutes the conflict the Charter prohibits.", evidence: "Garza holds VP role at UA Local 333 while serving as Chair of the Committee on Development and Planning — controlling agenda for votes involving union construction." },
      { num: 4, name: "Autonomy and Independence", violation: "Board relied on the city attorney's narrowed legal standard. The city attorney serves the mayor — who appoints council members' allies. Structurally, the city attorney cannot be an independent interpreter of conflict standards for the council.", evidence: "City Attorney Venker redefined test from Charter's 'any income or benefit, directly or indirectly' to 'direct contractual relationship' — narrower than Charter text." },
      { num: 5, name: "Education, Training, and Information", violation: "Board declined to establish guidance on conflict standards for future similar situations. Future complainants have no precedent to cite. The Charter's conflict provisions remain operationally undefined.", evidence: "Board motion stated it would 'not provide an opinion at this time, as the matter is no longer ripe' — a ripeness standard not part of the original filing." },
      { num: 6, name: "Cooperation Among Cooperatives", violation: "Board did not reference peer ethics bodies, established conflict-of-interest frameworks, or model ordinances from other Michigan cities that have addressed financial-interest conflicts.", evidence: "Insufficient evidence in available reporting." },
      { num: 7, name: "Concern for Community", violation: "Effective nullification of the Charter's conflict standard removes protection for all future community members who file legitimate ethics complaints. The precedent set is that the test can be administratively narrowed.", evidence: "Deep Green withdrawal cited as making complaint moot — ignoring requesters' documented concern about ongoing conflict in future votes." },
    ],
    ownership: [
      { question: "Who owns it?", before: "Ethics oversight process (community protection mechanism)", after: "City attorney's interpretation — a narrower test than Charter text", assessment: "extractive" },
      { question: "Who has power?", before: "Board of Ethics (nominally independent)", after: "City attorney's legal framework, which the Board accepted without explanation", assessment: "extractive" },
      { question: "Who benefits?", before: "Community (fair ethics enforcement, clear standards)", after: "Council members with financial conflicts who can continue voting without defined precedent", assessment: "extractive" },
      { question: "Who does the work?", before: "Board members (responding to 4 legitimate complaints)", after: "Zero output — complaint declined, no opinion, no precedent", assessment: "extractive" },
      { question: "Who makes the rules?", before: "Lansing City Charter", after: "City attorney (who rewrote the operative test without public deliberation)", assessment: "extractive" },
    ],
    bottomLines: [
      { dimension: "People", impact: "negative", description: "Four community members who used a legitimate process received no ruling. Future complainants have no established precedent to cite. Charter protections are operationally void until the Board issues guidance." },
      { dimension: "Planet", impact: "insufficient", description: "Insufficient evidence to assess environmental impact from this decision." },
      { dimension: "Prosperity", impact: "negative", description: "Conflict-of-interest protections exist to ensure public money goes to public benefit. Nullifying them enables continued extraction through council votes where members hold financial interests." },
      { dimension: "Purpose", impact: "negative", description: "An ethics board that declines to rule on documented conflicts — by voice vote, using a legal standard narrower than the Charter — has inverted its purpose. The institution exists to define these boundaries, not to avoid them." },
    ],
    scoreTransparency: "concerning",
    scoreConflicts: "high-risk",
    scoreMission: "high-risk",
    scoreDemocraticControl: "concerning",
    scoreOversight: "insufficient",
    sections: [],
    recommendations: [
      "Require roll call votes on all Board of Ethics decisions — voice votes on conflict rulings are incompatible with public accountability",
      "Adopt a written conflict-of-interest policy operationalizing the Charter standard — define 'income or benefit, directly or indirectly' with examples",
      "Require mandatory recusal and public recusal statements when council members vote on matters involving their employers or salary sources",
      "Establish an independent ethics officer (not the city attorney) to advise the Board — the city attorney serves the mayor, creating structural conflict",
      "Issue advisory opinions proactively on standing conflict situations — waiting for individual complaints allows ongoing conflicts to continue unaddressed",
    ],
    sources: [
      "Rhinoceros Media. \"Lansing Board of Ethics Declines to Issue Opinion on Council Member's Potential Conflicts.\"",
      "Lansing City Charter — conflict-of-interest provisions.",
      "Board of Ethics meeting minutes, April 14, 2026.",
      "Michigan Pipe Trades Association — public compensation records.",
    ],
    sourceUrls: ["https://rhinocerosmedia.org/garza-boe-declined"],
  },
];

async function main() {
  for (const s of studies) {
    await prisma.boardCaseStudy.upsert({
      where: { slug: s.slug },
      update: s,
      create: s,
    });
    console.log(`✓ ${s.boardName}`);
  }
  console.log(`\nSeeded ${studies.length} case studies.`);
}

main()
  .catch(e => { console.error(e); process.exit(1); })
  .finally(() => prisma.$disconnect());
